### ISSUE TITLE
stateOfCSS mailto without email

### ISSUE THREAD

**Issue by idotj** [StateOfJS/Monorepo#49]
Hi,
I would like to contact the team after reading the survey, but the link at the bottom has a mailto without any email address inside.

`mailto:?subject=The State of CSS 2021 Survey Results&body=Here are some interesting survey results: https://2021.stateofcss.com`

*I didn't find the stateOfCSS2021 to publish this issue ( I have just clicked at the bottom link of the website "_Found a bug? Leave an issue_" ).

**Comment by SachaG** [comment]
That's not a contact link, that's a link to email the survey to somebody else. Sorry for the confusion.
