### ISSUE TITLE
State of css color-contrast link broken

### ISSUE THREAD

**Issue by eddhurst** [StateOfJS/Monorepo#51]
The link to CanIUse is broken for the section on color-contrast on the Accessibility page.
https://2021.stateofcss.com/en-US/features/accessibility/

Feels like it's probably a typo, but on the off chance it's me, I'm using Firefox mobile, on Android.

Ought to be the link: https://caniuse.com/mdn-css_types_color_color-contrast

**Comment by SachaG** [comment]
Thanks!
