### ISSUE TITLE
GraphQL link in api readme points to localhost

### ISSUE THREAD

**Issue by ButterCheezii** [StateOfJS/Monorepo#55]
https://github.com/StateOfJS/Monorepo/blob/f1d5860848312b85f1993f5eebf1e540d1a8359d/api/README.md#L45

**Comment by SachaG** [comment]
Yes because this is documentation about running the API locally.

**Comment by ButterCheezii** [comment]
It would be helpful to note that url becomes available only while running the dev server, if it's not a mistake.
