### ISSUE TITLE
The monorepo.tools should be a recommended resource

### ISSUE THREAD

**Issue by meeroslav** [StateOfJS/Monorepo#72]
On the report part related to Monorepo tools (https://2021.stateofjs.com/en-US/libraries/monorepo-tools/), the recommended resources features outdated training from Frontend Masters.

I believe the link to [monorepo.tools](https://monorepo.tools/), _de facto_ most up-to-date overview of the modern monorepo solutions, maintained by monorepo creators themselves provide more relevant information.

Unless these are paid adverts, in which case the "Recommended resources" is a bit misleading.

**Comment by SachaG** [comment]
That's a great resource but those resource links are sponsored links from our partner Frontend Masters. If monorepo.tools is interested in supporting the survey I can definitely add the link there though.

**Comment by meeroslav** [comment]
The `monorepo.tools` unfortunately is an open-source website whose domain is sponsored by @nrwl, so not really capable of sponsoring anything 😀 

Thanks for the response
