### ISSUE TITLE
"Other Disabilities" data label error

### ISSUE THREAD

**Issue by samhenrigold** [StateOfJS/Monorepo#75]
The label for carpal tunnel seems to be incorrect, it looks like a query that got accidentally turned into a string. https://2021.stateofjs.com/en-US/demographics/#disability_status_others

<img width="862" alt="Screen Shot 2022-02-16 at 4 23 32 PM" src="https://user-images.githubusercontent.com/49251320/154359479-19800088-0792-4490-bb1f-7b9d4eb0b1be.png">

**Comment by SachaG** [comment]
Good catch, the translations was missing.
