### ISSUE TITLE
chart title is short in the Japanese version

### ISSUE THREAD

**Issue by myakura** [StateOfJS/Monorepo#83]
This is the CSS library evaluation chart in the Japanese version: 

![Screenshot](https://user-images.githubusercontent.com/413984/156908459-0a088d98-963b-483d-a577-594244a2ad46.png)

And here's the same section in the English version:

![Screen Shot 2022-03-06 at 12 50 39](https://user-images.githubusercontent.com/413984/156908480-11e5428f-3369-4841-bddf-de0abdf53c69.png)

Somehow the widths of titles in the Japanese version is about half the size of those in the English version. Since the width is narrower, some titles (in this case, "ドキュメンテーション",  "アクセシビリティ", and "ユーザーベース") are chopped.

There might be no choice if the strings are too large... but unlike the English version, those Japanese title are not truncated with ellipsis, and are right-aligned with no scrolling mechanism. So there's no way to see the start of the string, making it hard to get the meaning of those long titles.

**Comment by SachaG** [comment]
This is because the calculation to decide to truncate or not is just based on number of characters (because this is inside a SVG), and Japanese characters are larger, maybe because it's using a fallback font and not IBM Plex Mono? I think I need to change it so that it's based on the actual width of the element in the DOM.

**Comment by SachaG** [comment]
Since this would be fairly complex I think it's actually better to leave like that for now and eventually redo the entire chart in HTML/CSS, which will solve this issue and others at the same time.

**Comment by myakura** [comment]
> This is because the calculation to decide to truncate or not is just based on number of characters (because this is inside a SVG), and Japanese characters are larger, maybe because it's using a fallback font and not IBM Plex Mono? I think I need to change it so that it's based on the actual width of the element in the DOM.

Thanks for taking a look. I opened DevTools and saw a bunch of `<g>` elements then gave up :)

> Since this would be fairly complex I think it's actually better to leave like that for now and eventually redo the entire chart in HTML/CSS, which will solve this issue and others at the same time.

Okay. I'll try to use shorter text for titles.
